/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export interface City {
  'region' : string,
  'latitude' : number,
  'country' : string,
  'name' : string,
  'longitude' : number,
}
export interface CleanAction { 'times' : bigint, 'toolId' : string }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface GameState {
  'status' : GameStatus,
  'money' : bigint,
  'tools' : Array<ToolUpgrade>,
  'initialPollution' : bigint,
  'city' : City,
  'npcs' : Array<Npc>,
  'turn' : bigint,
  'pollution' : bigint,
  'updatedAt' : Timestamp,
  'totalRemoved' : bigint,
  'actionsLeft' : bigint,
}
export type GameStatus = { 'won' : null } |
  { 'lost' : null } |
  { 'playing' : null };
export type NewGameError = { 'invalidCity' : null };
export interface Npc { 'id' : string, 'count' : bigint }
export type PlayerId = Principal;
export interface RankingEntry {
  'player' : PlayerId,
  'turn' : bigint,
  'cityName' : string,
  'totalRemoved' : bigint,
}
export interface RankingView {
  'callerRank' : [] | [bigint],
  'entries' : Array<RankingEntry>,
  'callerEntry' : [] | [RankingEntry],
}
export type Result = { 'ok' : GameState } |
  { 'err' : ShopError };
export type Result_1 = { 'ok' : GameState } |
  { 'err' : NewGameError };
export type Result_2 = { 'ok' : TurnResult } |
  { 'err' : TurnError };
export type Result_3 = { 'ok' : null } |
  { 'err' : Error };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type ShopError = {
    'insufficientFunds' : { 'available' : bigint, 'required' : bigint }
  } |
  { 'unknownItem' : string } |
  { 'gameOver' : null };
export interface ShopItem {
  'id' : string,
  'owned' : bigint,
  'kind' : ShopItemKind,
  'name' : string,
  'description' : string,
  'power' : bigint,
  'price' : bigint,
}
export type ShopItemKind = { 'npc' : null } |
  { 'tool' : null };
export type Timestamp = bigint;
export interface ToolUpgrade { 'id' : string, 'level' : bigint }
export type TurnError = { 'noActionsLeft' : null } |
  { 'noGame' : null } |
  { 'unknownTool' : string } |
  { 'gameOver' : null };
export interface TurnEvent {
  'kind' : string,
  'message' : string,
  'amount' : bigint,
}
export interface TurnResult {
  'pollutionRemoved' : bigint,
  'state' : GameState,
  'events' : Array<TurnEvent>,
  'moneyEarned' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_3>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Resolve the current turn with the caller's chosen cleaning actions.
   */
  'endTurn' : ActorMethod<[Array<CleanAction>], Result_2>,
  'execute' : ActorMethod<[string], Result__1>,
  /**
   * / Static Markdown description of this canister's public API.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Return the caller's saved game, or `null` when none exists.
   */
  'getGame' : ActorMethod<[], [] | [GameState]>,
  /**
   * / Global leaderboard ordered by total pollution removed, including the
   * / caller's own rank when they have a saved game.
   */
  'getRanking' : ActorMethod<[bigint], RankingView>,
  /**
   * / Return the shop catalogue priced for the caller's current state.
   */
  'getShop' : ActorMethod<[], Array<ShopItem>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Start a fresh game for the caller with a newly chosen city. Replaces any
   * / existing saved game. Anonymous callers are rejected.
   */
  'newGame' : ActorMethod<[City, bigint, bigint], Result_1>,
  /**
   * / Buy a tool upgrade or an NPC with the caller's money.
   */
  'purchase' : ActorMethod<[string], Result>,
  /**
   * / Delete the caller's saved game and start over from the city selection.
   */
  'resetGame' : ActorMethod<[], undefined>,
  'schema' : ActorMethod<[], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];