/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result_3 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CleanAction = IDL.Record({
  'times' : IDL.Nat,
  'toolId' : IDL.Text,
});
export const GameStatus = IDL.Variant({
  'won' : IDL.Null,
  'lost' : IDL.Null,
  'playing' : IDL.Null,
});
export const ToolUpgrade = IDL.Record({ 'id' : IDL.Text, 'level' : IDL.Nat });
export const City = IDL.Record({
  'region' : IDL.Text,
  'latitude' : IDL.Float64,
  'country' : IDL.Text,
  'name' : IDL.Text,
  'longitude' : IDL.Float64,
});
export const Npc = IDL.Record({ 'id' : IDL.Text, 'count' : IDL.Nat });
export const Timestamp = IDL.Int;
export const GameState = IDL.Record({
  'status' : GameStatus,
  'money' : IDL.Nat,
  'tools' : IDL.Vec(ToolUpgrade),
  'initialPollution' : IDL.Nat,
  'city' : City,
  'npcs' : IDL.Vec(Npc),
  'turn' : IDL.Nat,
  'pollution' : IDL.Nat,
  'updatedAt' : Timestamp,
  'totalRemoved' : IDL.Nat,
  'actionsLeft' : IDL.Nat,
});
export const TurnEvent = IDL.Record({
  'kind' : IDL.Text,
  'message' : IDL.Text,
  'amount' : IDL.Nat,
});
export const TurnResult = IDL.Record({
  'pollutionRemoved' : IDL.Nat,
  'state' : GameState,
  'events' : IDL.Vec(TurnEvent),
  'moneyEarned' : IDL.Nat,
});
export const TurnError = IDL.Variant({
  'noActionsLeft' : IDL.Null,
  'noGame' : IDL.Null,
  'unknownTool' : IDL.Text,
  'gameOver' : IDL.Null,
});
export const Result_2 = IDL.Variant({ 'ok' : TurnResult, 'err' : TurnError });
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const PlayerId = IDL.Principal;
export const RankingEntry = IDL.Record({
  'player' : PlayerId,
  'turn' : IDL.Nat,
  'cityName' : IDL.Text,
  'totalRemoved' : IDL.Nat,
});
export const RankingView = IDL.Record({
  'callerRank' : IDL.Opt(IDL.Nat),
  'entries' : IDL.Vec(RankingEntry),
  'callerEntry' : IDL.Opt(RankingEntry),
});
export const ShopItemKind = IDL.Variant({
  'npc' : IDL.Null,
  'tool' : IDL.Null,
});
export const ShopItem = IDL.Record({
  'id' : IDL.Text,
  'owned' : IDL.Nat,
  'kind' : ShopItemKind,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'power' : IDL.Nat,
  'price' : IDL.Nat,
});
export const NewGameError = IDL.Variant({ 'invalidCity' : IDL.Null });
export const Result_1 = IDL.Variant({ 'ok' : GameState, 'err' : NewGameError });
export const ShopError = IDL.Variant({
  'insufficientFunds' : IDL.Record({
    'available' : IDL.Nat,
    'required' : IDL.Nat,
  }),
  'unknownItem' : IDL.Text,
  'gameOver' : IDL.Null,
});
export const Result = IDL.Variant({ 'ok' : GameState, 'err' : ShopError });

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result_3], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'endTurn' : IDL.Func([IDL.Vec(CleanAction)], [Result_2], []),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGame' : IDL.Func([], [IDL.Opt(GameState)], ['query']),
  'getRanking' : IDL.Func([IDL.Nat], [RankingView], ['query']),
  'getShop' : IDL.Func([], [IDL.Vec(ShopItem)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'newGame' : IDL.Func([City, IDL.Nat, IDL.Nat], [Result_1], []),
  'purchase' : IDL.Func([IDL.Text], [Result], []),
  'resetGame' : IDL.Func([], [], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result_3 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CleanAction = IDL.Record({ 'times' : IDL.Nat, 'toolId' : IDL.Text });
  const GameStatus = IDL.Variant({
    'won' : IDL.Null,
    'lost' : IDL.Null,
    'playing' : IDL.Null,
  });
  const ToolUpgrade = IDL.Record({ 'id' : IDL.Text, 'level' : IDL.Nat });
  const City = IDL.Record({
    'region' : IDL.Text,
    'latitude' : IDL.Float64,
    'country' : IDL.Text,
    'name' : IDL.Text,
    'longitude' : IDL.Float64,
  });
  const Npc = IDL.Record({ 'id' : IDL.Text, 'count' : IDL.Nat });
  const Timestamp = IDL.Int;
  const GameState = IDL.Record({
    'status' : GameStatus,
    'money' : IDL.Nat,
    'tools' : IDL.Vec(ToolUpgrade),
    'initialPollution' : IDL.Nat,
    'city' : City,
    'npcs' : IDL.Vec(Npc),
    'turn' : IDL.Nat,
    'pollution' : IDL.Nat,
    'updatedAt' : Timestamp,
    'totalRemoved' : IDL.Nat,
    'actionsLeft' : IDL.Nat,
  });
  const TurnEvent = IDL.Record({
    'kind' : IDL.Text,
    'message' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const TurnResult = IDL.Record({
    'pollutionRemoved' : IDL.Nat,
    'state' : GameState,
    'events' : IDL.Vec(TurnEvent),
    'moneyEarned' : IDL.Nat,
  });
  const TurnError = IDL.Variant({
    'noActionsLeft' : IDL.Null,
    'noGame' : IDL.Null,
    'unknownTool' : IDL.Text,
    'gameOver' : IDL.Null,
  });
  const Result_2 = IDL.Variant({ 'ok' : TurnResult, 'err' : TurnError });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const PlayerId = IDL.Principal;
  const RankingEntry = IDL.Record({
    'player' : PlayerId,
    'turn' : IDL.Nat,
    'cityName' : IDL.Text,
    'totalRemoved' : IDL.Nat,
  });
  const RankingView = IDL.Record({
    'callerRank' : IDL.Opt(IDL.Nat),
    'entries' : IDL.Vec(RankingEntry),
    'callerEntry' : IDL.Opt(RankingEntry),
  });
  const ShopItemKind = IDL.Variant({ 'npc' : IDL.Null, 'tool' : IDL.Null });
  const ShopItem = IDL.Record({
    'id' : IDL.Text,
    'owned' : IDL.Nat,
    'kind' : ShopItemKind,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'power' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const NewGameError = IDL.Variant({ 'invalidCity' : IDL.Null });
  const Result_1 = IDL.Variant({ 'ok' : GameState, 'err' : NewGameError });
  const ShopError = IDL.Variant({
    'insufficientFunds' : IDL.Record({
      'available' : IDL.Nat,
      'required' : IDL.Nat,
    }),
    'unknownItem' : IDL.Text,
    'gameOver' : IDL.Null,
  });
  const Result = IDL.Variant({ 'ok' : GameState, 'err' : ShopError });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result_3], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'endTurn' : IDL.Func([IDL.Vec(CleanAction)], [Result_2], []),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGame' : IDL.Func([], [IDL.Opt(GameState)], ['query']),
    'getRanking' : IDL.Func([IDL.Nat], [RankingView], ['query']),
    'getShop' : IDL.Func([], [IDL.Vec(ShopItem)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'newGame' : IDL.Func([City, IDL.Nat, IDL.Nat], [Result_1], []),
    'purchase' : IDL.Func([IDL.Text], [Result], []),
    'resetGame' : IDL.Func([], [], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };