/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface Cell {
    value: Value;
    name: string;
}
export interface City {
    region: string;
    latitude: number;
    country: string;
    name: string;
    longitude: number;
}
export interface CleanAction {
    times: bigint;
    toolId: string;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface GameState {
    status: GameStatus;
    money: bigint;
    tools: Array<ToolUpgrade>;
    initialPollution: bigint;
    city: City;
    npcs: Array<Npc>;
    turn: bigint;
    pollution: bigint;
    updatedAt: Timestamp;
    totalRemoved: bigint;
    actionsLeft: bigint;
}
export interface Npc {
    id: string;
    count: bigint;
}
export type PlayerId = Principal;
export interface RankingEntry {
    player: PlayerId;
    turn: bigint;
    cityName: string;
    totalRemoved: bigint;
}
export interface RankingView {
    callerRank?: bigint;
    entries: Array<RankingEntry>;
    callerEntry?: RankingEntry;
}
export type Result = {
    __kind__: "ok";
    ok: GameState;
} | {
    __kind__: "err";
    err: ShopError;
};
export type Result_1 = {
    __kind__: "ok";
    ok: GameState;
} | {
    __kind__: "err";
    err: NewGameError;
};
export type Result_2 = {
    __kind__: "ok";
    ok: TurnResult;
} | {
    __kind__: "err";
    err: TurnError;
};
export type Result_3 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface Result__1 {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type ShopError = {
    __kind__: "insufficientFunds";
    insufficientFunds: {
        available: bigint;
        required: bigint;
    };
} | {
    __kind__: "unknownItem";
    unknownItem: string;
} | {
    __kind__: "gameOver";
    gameOver: null;
};
export interface ShopItem {
    id: string;
    owned: bigint;
    kind: ShopItemKind;
    name: string;
    description: string;
    power: bigint;
    price: bigint;
}
export type Timestamp = bigint;
export interface ToolUpgrade {
    id: string;
    level: bigint;
}
export type TurnError = {
    __kind__: "noActionsLeft";
    noActionsLeft: null;
} | {
    __kind__: "noGame";
    noGame: null;
} | {
    __kind__: "unknownTool";
    unknownTool: string;
} | {
    __kind__: "gameOver";
    gameOver: null;
};
export interface TurnEvent {
    kind: string;
    message: string;
    amount: bigint;
}
export interface TurnResult {
    pollutionRemoved: bigint;
    state: GameState;
    events: Array<TurnEvent>;
    moneyEarned: bigint;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export enum GameStatus {
    won = "won",
    lost = "lost",
    playing = "playing"
}
export enum NewGameError {
    invalidCity = "invalidCity"
}
export enum ShopItemKind {
    npc = "npc",
    tool = "tool"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result_3>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Resolve the current turn with the caller's chosen cleaning actions.
     */
    endTurn(actions: Array<CleanAction>): Promise<Result_2>;
    execute(qJson: string): Promise<Result__1>;
    /**
     * / Static Markdown description of this canister's public API.
     */
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Return the caller's saved game, or `null` when none exists.
     */
    getGame(): Promise<GameState | null>;
    /**
     * / Global leaderboard ordered by total pollution removed, including the
     * / caller's own rank when they have a saved game.
     */
    getRanking(limit: bigint): Promise<RankingView>;
    /**
     * / Return the shop catalogue priced for the caller's current state.
     */
    getShop(): Promise<Array<ShopItem>>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / Start a fresh game for the caller with a newly chosen city. Replaces any
     * / existing saved game. Anonymous callers are rejected.
     */
    newGame(city: City, initialPollution: bigint, startingMoney: bigint): Promise<Result_1>;
    /**
     * / Buy a tool upgrade or an NPC with the caller's money.
     */
    purchase(itemId: string): Promise<Result>;
    /**
     * / Delete the caller's saved game and start over from the city selection.
     */
    resetGame(): Promise<void>;
    schema(): Promise<string>;
}
import type { Cell as _Cell, City as _City, Error as _Error, GameState as _GameState, GameStatus as _GameStatus, NewGameError as _NewGameError, Npc as _Npc, RankingEntry as _RankingEntry, RankingView as _RankingView, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result__1 as _Result__1, ShopError as _ShopError, ShopItem as _ShopItem, ShopItemKind as _ShopItemKind, Timestamp as _Timestamp, ToolUpgrade as _ToolUpgrade, TurnError as _TurnError, TurnEvent as _TurnEvent, TurnResult as _TurnResult, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result_3_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result_3_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async endTurn(arg0: Array<CleanAction>): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.endTurn(arg0);
                return from_candid_Result_2_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endTurn(arg0);
            return from_candid_Result_2_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async execute(arg0: string): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result__1_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result__1_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGame(): Promise<GameState | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGame();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGame();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRanking(arg0: bigint): Promise<RankingView> {
        if (this.processError) {
            try {
                const result = await this.actor.getRanking(arg0);
                return from_candid_RankingView_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRanking(arg0);
            return from_candid_RankingView_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShop(): Promise<Array<ShopItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShop();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShop();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async newGame(arg0: City, arg1: bigint, arg2: bigint): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.newGame(arg0, arg1, arg2);
                return from_candid_Result_1_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.newGame(arg0, arg1, arg2);
            return from_candid_Result_1_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async purchase(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.purchase(arg0);
                return from_candid_Result_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchase(arg0);
            return from_candid_Result_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetGame(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetGame();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetGame();
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
}
function from_candid_Cell_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_GameState_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameState): GameState {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_GameStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameStatus): GameStatus {
    return "won" in value ? GameStatus.won : "lost" in value ? GameStatus.lost : "playing" in value ? GameStatus.playing : value;
}
function from_candid_NewGameError_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NewGameError): NewGameError {
    return "invalidCity" in value ? NewGameError.invalidCity : value;
}
function from_candid_RankingView_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RankingView): RankingView {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_ShopError_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShopError): ShopError {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_ShopItemKind_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShopItemKind): ShopItemKind {
    return "npc" in value ? ShopItemKind.npc : "tool" in value ? ShopItemKind.tool : value;
}
function from_candid_ShopItem_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShopItem): ShopItem {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_TurnError_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TurnError): TurnError {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_TurnResult_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TurnResult): TurnResult {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GameState]): GameState | null {
    return value.length === 0 ? null : from_candid_GameState_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RankingEntry]): RankingEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _GameStatus;
    money: bigint;
    tools: Array<_ToolUpgrade>;
    initialPollution: bigint;
    city: _City;
    npcs: Array<_Npc>;
    turn: bigint;
    pollution: bigint;
    updatedAt: _Timestamp;
    totalRemoved: bigint;
    actionsLeft: bigint;
}): {
    status: GameStatus;
    money: bigint;
    tools: Array<ToolUpgrade>;
    initialPollution: bigint;
    city: City;
    npcs: Array<Npc>;
    turn: bigint;
    pollution: bigint;
    updatedAt: Timestamp;
    totalRemoved: bigint;
    actionsLeft: bigint;
} {
    return {
        status: from_candid_GameStatus_n12(_uploadFile, _downloadFile, value.status),
        money: value.money,
        tools: value.tools,
        initialPollution: value.initialPollution,
        city: value.city,
        npcs: value.npcs,
        turn: value.turn,
        pollution: value.pollution,
        updatedAt: value.updatedAt,
        totalRemoved: value.totalRemoved,
        actionsLeft: value.actionsLeft
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n17(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n21(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    callerRank: [] | [bigint];
    entries: Array<_RankingEntry>;
    callerEntry: [] | [_RankingEntry];
}): {
    callerRank?: bigint;
    entries: Array<RankingEntry>;
    callerEntry?: RankingEntry;
} {
    return {
        callerRank: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.callerRank)),
        entries: value.entries,
        callerEntry: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.callerEntry))
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    owned: bigint;
    kind: _ShopItemKind;
    name: string;
    description: string;
    power: bigint;
    price: bigint;
}): {
    id: string;
    owned: bigint;
    kind: ShopItemKind;
    name: string;
    description: string;
    power: bigint;
    price: bigint;
} {
    return {
        id: value.id,
        owned: value.owned,
        kind: from_candid_ShopItemKind_n32(_uploadFile, _downloadFile, value.kind),
        name: value.name,
        description: value.description,
        power: value.power,
        price: value.price
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pollutionRemoved: bigint;
    state: _GameState;
    events: Array<_TurnEvent>;
    moneyEarned: bigint;
}): {
    pollutionRemoved: bigint;
    state: GameState;
    events: Array<TurnEvent>;
    moneyEarned: bigint;
} {
    return {
        pollutionRemoved: value.pollutionRemoved,
        state: from_candid_GameState_n10(_uploadFile, _downloadFile, value.state),
        events: value.events,
        moneyEarned: value.moneyEarned
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    noActionsLeft: null;
} | {
    noGame: null;
} | {
    unknownTool: string;
} | {
    gameOver: null;
}): {
    __kind__: "noActionsLeft";
    noActionsLeft: null;
} | {
    __kind__: "noGame";
    noGame: null;
} | {
    __kind__: "unknownTool";
    unknownTool: string;
} | {
    __kind__: "gameOver";
    gameOver: null;
} {
    return "noActionsLeft" in value ? {
        __kind__: "noActionsLeft",
        noActionsLeft: value.noActionsLeft
    } : "noGame" in value ? {
        __kind__: "noGame",
        noGame: value.noGame
    } : "unknownTool" in value ? {
        __kind__: "unknownTool",
        unknownTool: value.unknownTool
    } : "gameOver" in value ? {
        __kind__: "gameOver",
        gameOver: value.gameOver
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _GameState;
} | {
    err: _NewGameError;
}): {
    __kind__: "ok";
    ok: GameState;
} | {
    __kind__: "err";
    err: NewGameError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_GameState_n10(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_NewGameError_n35(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _GameState;
} | {
    err: _ShopError;
}): {
    __kind__: "ok";
    ok: GameState;
} | {
    __kind__: "err";
    err: ShopError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_GameState_n10(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_ShopError_n38(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    insufficientFunds: {
        available: bigint;
        required: bigint;
    };
} | {
    unknownItem: string;
} | {
    gameOver: null;
}): {
    __kind__: "insufficientFunds";
    insufficientFunds: {
        available: bigint;
        required: bigint;
    };
} | {
    __kind__: "unknownItem";
    unknownItem: string;
} | {
    __kind__: "gameOver";
    gameOver: null;
} {
    return "insufficientFunds" in value ? {
        __kind__: "insufficientFunds",
        insufficientFunds: value.insufficientFunds
    } : "unknownItem" in value ? {
        __kind__: "unknownItem",
        unknownItem: value.unknownItem
    } : "gameOver" in value ? {
        __kind__: "gameOver",
        gameOver: value.gameOver
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _TurnResult;
} | {
    err: _TurnError;
}): {
    __kind__: "ok";
    ok: TurnResult;
} | {
    __kind__: "err";
    err: TurnError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_TurnResult_n8(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_TurnError_n13(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ShopItem>): Array<ShopItem> {
    return value.map((x)=>from_candid_ShopItem_n30(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
